"""add persistent scheduler

Revision ID: 648ceacce0c4
Revises: fcc6aa802526
Create Date: 2026-08-25 18:36:57.385557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '648ceacce0c4'
down_revision: Union[str, Sequence[str], None] = 'fcc6aa802526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job_code', sa.String(length=100), nullable=False),
    sa.Column('run_key', sa.String(length=50), nullable=False),
    sa.Column('target_local_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_code', 'run_key', name='uq_job_run_key')
    )
    op.create_table('scheduled_jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('local_hour', sa.Integer(), nullable=False),
    sa.Column('local_minute', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduled_jobs')
    op.drop_table('job_runs')
    # ### end Alembic commands ###
