"""add skill progression tables

Revision ID: 866421b001c9
Revises: 5bd0d317f9f7
Create Date: 2026-08-25 17:27:07.157070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '866421b001c9'
down_revision: Union[str, Sequence[str], None] = '5bd0d317f9f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_progression_versions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('skill_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', 'version', name='uq_skill_progression_version')
    )
    op.create_table('skill_level_thresholds',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('progression_version_id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('cumulative_xp_required', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['progression_version_id'], ['skill_progression_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('progression_version_id', 'level', name='uq_progression_level')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill_level_thresholds')
    op.drop_table('skill_progression_versions')
    # ### end Alembic commands ###
