"""add quests habits and bulk tracking

Revision ID: b3a97ab8e8d2
Revises: fc629fccbb50
Create Date: 2026-08-25 18:16:27.045672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3a97ab8e8d2'
down_revision: Union[str, Sequence[str], None] = 'fc629fccbb50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrition_daily',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('base_target_kcal', sa.Integer(), nullable=False),
    sa.Column('adjusted_target_kcal', sa.Integer(), nullable=True),
    sa.Column('target_reached', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('local_date')
    )
    op.create_table('weight_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('weight_g', sa.Integer(), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habits',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('skill_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('minimum_minutes', sa.Integer(), nullable=True),
    sa.Column('true_streak', sa.Boolean(), nullable=False),
    sa.Column('affects_disc', sa.Boolean(), nullable=False),
    sa.Column('grants_skill_xp', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('quests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('quest_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('skill_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_value', sa.Integer(), nullable=True),
    sa.Column('target_unit', sa.String(length=30), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('habit_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('habit_id', sa.BigInteger(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('value_int', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'local_date', name='uq_habit_log_day')
    )
    op.create_table('quest_instances',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('quest_id', sa.BigInteger(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('load', sa.Integer(), nullable=False),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_target', sa.Integer(), nullable=False),
    sa.Column('skipped_reason_primary', sa.String(length=50), nullable=True),
    sa.Column('skipped_reason_secondary', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quest_id', 'local_date', name='uq_quest_instance_day')
    )
    op.create_table('quest_schedules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('quest_id', sa.BigInteger(), nullable=False),
    sa.Column('cadence', sa.String(length=20), nullable=False),
    sa.Column('minimum_required', sa.Integer(), nullable=True),
    sa.Column('stretch_target', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quest_id', 'cadence', name='uq_quest_schedule_cadence')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quest_schedules')
    op.drop_table('quest_instances')
    op.drop_table('habit_logs')
    op.drop_table('quests')
    op.drop_table('habits')
    op.drop_table('weight_logs')
    op.drop_table('nutrition_daily')
    # ### end Alembic commands ###
