"""add achievements timeline reports

Revision ID: c7a5970a6008
Revises: 648ceacce0c4
Create Date: 2026-08-25 18:44:31.390645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a5970a6008'
down_revision: Union[str, Sequence[str], None] = '648ceacce0c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('rarity', sa.String(length=30), nullable=False),
    sa.Column('secret', sa.Boolean(), nullable=False),
    sa.Column('criteria_type', sa.String(length=50), nullable=False),
    sa.Column('criteria_skill_code', sa.String(length=100), nullable=True),
    sa.Column('threshold_value', sa.Integer(), nullable=False),
    sa.Column('threshold_unit', sa.String(length=50), nullable=True),
    sa.Column('cxp_reward', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('reports',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('report_type', sa.String(length=30), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_type', 'period_start', 'period_end', 'version', name='uq_report_version')
    )
    op.create_table('timeline_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_key', sa.String(length=150), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('significance', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key')
    )
    op.create_table('achievement_unlocks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('achievement_id', sa.BigInteger(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('achievement_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('achievement_unlocks')
    op.drop_table('timeline_events')
    op.drop_table('reports')
    op.drop_table('achievements')
    # ### end Alembic commands ###
