"""add daily snapshots and streaks

Revision ID: fcc6aa802526
Revises: b3a97ab8e8d2
Create Date: 2026-08-25 18:27:55.473787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcc6aa802526'
down_revision: Union[str, Sequence[str], None] = 'b3a97ab8e8d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('russian_state', sa.String(length=20), nullable=True),
    sa.Column('nutrition_state', sa.String(length=20), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_manually', sa.Boolean(), nullable=False),
    sa.Column('disc_ranked', sa.Boolean(), nullable=False),
    sa.Column('disc_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('local_date')
    )
    op.create_table('streak_state',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('habit_id', sa.BigInteger(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('best_streak', sa.Integer(), nullable=False),
    sa.Column('rate_7_bp', sa.Integer(), nullable=True),
    sa.Column('rate_30_bp', sa.Integer(), nullable=True),
    sa.Column('rate_90_bp', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id')
    )
    op.add_column(
        'habit_logs',
        sa.Column(
            'finalized_by_close',
            sa.Boolean(),
            server_default=sa.false(),
            nullable=False,
        ),
    )
    op.alter_column(
        'habit_logs',
        'finalized_by_close',
        server_default=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habit_logs', 'finalized_by_close')
    op.drop_table('streak_state')
    op.drop_table('daily_snapshots')
    # ### end Alembic commands ###
